export const MILLIS_PER_SECONDS = 1000
export const SECONDS_PER_MINUTE = 60
export const MINUTES_PER_HOUR = 60
export const DAYS_PER_WEEK = 7
export const HOURS_PER_DAY = 24
export const SECONDS_PER_HOUR = SECONDS_PER_MINUTE * MINUTES_PER_HOUR
export const MILLIS_IN_HOUR = MINUTES_PER_HOUR * SECONDS_PER_MINUTE * MILLIS_PER_SECONDS
export const MILLIS_IN_WEEK = DAYS_PER_WEEK * HOURS_PER_DAY * MILLIS_IN_HOUR
